
version: '3'
services:
  exporter:
    build: ./
    #ports:
    #  - 9710:9710
    volumes:
      - ./fortigate-key.yaml:/config/fortigate-key.yaml
    command: ["-auth-file", "/config/fortigate-key.yaml", "-insecure"]
    restart: unless-stopped
    networks:
      - monitoring
networks:
  monitoring:
    external: true

